server {
    listen 80;
    server_tokens off;

    client_max_body_size 10M;

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/admin/;
    }

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000/api/;
    }

    location /api/docs/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/redoc.html;
    }

    location /media/ {
        alias /media/;
    }

    location /backend_static/ {
        alias /staticfiles/backend_static/;
    }

    location /static/ {
        alias /staticfiles/frontend_static/static/;
    }

    location / {
        alias /staticfiles/frontend_static/;
        index index.html;
        try_files $uri /index.html;
    }
}
